services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./backend:/var/www/html
    depends_on:
      - app
    networks:
      - backend
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=${HOST}

  app:
    image: biz-linker-php
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend

  db:
    image: postgres
    ports:
      - 5432:5432

networks:
  backend:
    driver: bridge
