services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/html
    depends_on:
      - app
    ports:
      - 80:80

  app:
    image: biz-linker-php
    volumes:
      - ./backend:/var/www/html

  reverb:
    image: biz-linker-reverb-php
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8080:8080

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis

volumes:
  db:
