services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./backend:/var/www/html
    depends_on:
      - app
    ports:
      - "8080:80"

  app:
    image: biz-linker-php
    volumes:
      - ./backend:/var/www/html

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
