name: Build and Push Docker Image

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for php
        id: php-image-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-php

      - name: Extract metadata (tags, labels) for nginx
        id: nginx-image-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-nginx

      - name: Extract metadata (tags, labels) for reverb
        id: php-reverb-image-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-nginx

      - name: Build and push php docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./docker/app/deploy.Dockerfile
          push: true
          tags: ${{ steps.php-image-meta.outputs.tags }}
          labels: ${{ steps.php-image-meta.outputs.labels }}

      - name: Build and push nginx docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./docker/nginx/deploy.Dockerfile
          push: true
          tags: ${{ steps.nginx-image-meta.outputs.tags }}
          labels: ${{ steps.nginx-image-meta.outputs.labels }}

      - name: Build and push reverb docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./docker/reverb/Dockerfile
          push: true
          tags: ${{ steps.php-reverb-image-meta.outputs.tags }}
          labels: ${{ steps.php-reverb-image-meta.outputs.labels }}
