name: Deploy

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for php
        id: php-image-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-php

      - name: Extract metadata (tags, labels) for nginx
        id: nginx-image-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-nginx

      - name: Docker compose
        uses: appleboy/ssh-action@v1.2.0
        env:
          PHP_IMAGE_REF: ${{ steps.php-image-meta.outputs.tags }}
          NGINX_IMAGE_REF: ${{ steps.nginx-image-meta.outputs.tags }}
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: cd  make up
